# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/knoos001/final-project-knoos001-rpurc002-btang031-nfuli001

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/knoos001/final-project-knoos001-rpurc002-btang031-nfuli001

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/knoos001/final-project-knoos001-rpurc002-btang031-nfuli001/CMakeFiles /home/csmajs/knoos001/final-project-knoos001-rpurc002-btang031-nfuli001/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/knoos001/final-project-knoos001-rpurc002-btang031-nfuli001/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named recommend

# Build rule for target.
recommend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 recommend
.PHONY : recommend

# fast build rule for target.
recommend/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/build
.PHONY : recommend/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

display.o: display.cpp.o

.PHONY : display.o

# target to build an object file
display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/display.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/display.cpp.o
.PHONY : display.cpp.o

display.i: display.cpp.i

.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/display.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s

.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/display.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/display.cpp.s
.PHONY : display.cpp.s

genre.o: genre.cpp.o

.PHONY : genre.o

# target to build an object file
genre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/genre.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/genre.cpp.o
.PHONY : genre.cpp.o

genre.i: genre.cpp.i

.PHONY : genre.i

# target to preprocess a source file
genre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/genre.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/genre.cpp.i
.PHONY : genre.cpp.i

genre.s: genre.cpp.s

.PHONY : genre.s

# target to generate assembly for a file
genre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/genre.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/genre.cpp.s
.PHONY : genre.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/main.cpp.s
.PHONY : main.cpp.s

mainFunctions.o: mainFunctions.cpp.o

.PHONY : mainFunctions.o

# target to build an object file
mainFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/mainFunctions.cpp.o
.PHONY : mainFunctions.cpp.o

mainFunctions.i: mainFunctions.cpp.i

.PHONY : mainFunctions.i

# target to preprocess a source file
mainFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/mainFunctions.cpp.i
.PHONY : mainFunctions.cpp.i

mainFunctions.s: mainFunctions.cpp.s

.PHONY : mainFunctions.s

# target to generate assembly for a file
mainFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/mainFunctions.cpp.s
.PHONY : mainFunctions.cpp.s

menu.o: menu.cpp.o

.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i

.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s

.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/menu.cpp.s
.PHONY : menu.cpp.s

movie.o: movie.cpp.o

.PHONY : movie.o

# target to build an object file
movie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/movie.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/movie.cpp.o
.PHONY : movie.cpp.o

movie.i: movie.cpp.i

.PHONY : movie.i

# target to preprocess a source file
movie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/movie.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/movie.cpp.i
.PHONY : movie.cpp.i

movie.s: movie.cpp.s

.PHONY : movie.s

# target to generate assembly for a file
movie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/movie.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/movie.cpp.s
.PHONY : movie.cpp.s

scan.o: scan.cpp.o

.PHONY : scan.o

# target to build an object file
scan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/scan.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/scan.cpp.o
.PHONY : scan.cpp.o

scan.i: scan.cpp.i

.PHONY : scan.i

# target to preprocess a source file
scan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/scan.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/scan.cpp.i
.PHONY : scan.cpp.i

scan.s: scan.cpp.s

.PHONY : scan.s

# target to generate assembly for a file
scan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/scan.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/recommend.dir/build.make CMakeFiles/recommend.dir/scan.cpp.s
.PHONY : scan.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... recommend"
	@echo "... test"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... genre.o"
	@echo "... genre.i"
	@echo "... genre.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainFunctions.o"
	@echo "... mainFunctions.i"
	@echo "... mainFunctions.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... movie.o"
	@echo "... movie.i"
	@echo "... movie.s"
	@echo "... scan.o"
	@echo "... scan.i"
	@echo "... scan.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

